apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    name: postgres
spec:
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: test
        - name: POSTGRES_DB
          value: test
        ports:
        - containerPort: 5432
        volumeMounts:
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - test
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - test
          initialDelaySeconds: 5
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    name: postgres

